# Copyright (c) 2012-2019 Sebastien Rombauts (sebastien.rombauts@gmail.com)

language: cpp
sudo: false

# Use Linux unless specified otherwise
os: linux

cache:
  apt: true

matrix:
  include:

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    - env: COMPILER=g++
      dist: trusty

    - env: COMPILER=g++
      dist: xenial

    - env: COMPILER=g++
      dist: bionic

    ##########################################################################
    # Clang on Linux
    ##########################################################################

    - env: COMPILER=clang++
      dist: trusty

    - env: COMPILER=clang++
      dist: xenial

    - env: COMPILER=clang++
      dist: bionic

    ##########################################################################
    # Clang on OSX
    ##########################################################################

    # Latest XCode
    - env: COMPILER=clang++
      os: osx

    # XCode 8.3
    - env: COMPILER=clang++
      os: osx
      osx_image: xcode8.3


before_install:
  # Set the ${CXX} variable properly
  - export CXX=${COMPILER}
  - ${CXX} --version

  # coveralls test coverage:
  - if [[ "$CXX" == "g++" ]]; then pip install --user cpp-coveralls ; fi

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -DSQLITECPP_USE_ASAN=ON -DSQLITECPP_USE_GCOV=ON -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON ..

# build examples, and run tests (ie make & make test)
script:
  - cmake --build .
  - ctest --verbose --output-on-failure

# generate and publish GCov coveralls results
after_success:
  - if [[ "$CXX" == "g++" ]]; then coveralls --root .. -e examples -e googletest -e sqlite3 -e tests -E ".*feature_tests.*" -E ".*CompilerId.*" --gcov-options '\-lp' ; fi
